name: couldai_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Sensors & Hardware
  sensors_plus: ^6.1.0
  camera: ^0.11.0+1
  flutter_blue_plus: ^1.32.0
  permission_handler: ^11.3.0
  
  # Audio & FFT
  mic_stream: ^1.0.1
  fftea: ^1.4.0
  
  # Visualization
  syncfusion_flutter_charts: ^24.1.41
  
  # Audio Playback (for White Noise "Jamming")
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
